---
- name: Dnf cache
  ansible.builtin.yum_repository:
    update_cache: true

- name: Update
  ansible.builtin.yum_repository:
    state: latest

- name: Packages
  ansible.builtin.yum_repository:
    name:
      - btop
      - fastfetch
      - curl
      - wget
      - nginx

- name: Check if user in docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
