---
- name: Dnf cache
  ansible.builtin.dnf:
    update_cache: true

- name: Update packages
  ansible.builtin.dnf:
    name: '*'
    state: latest

- name: Packages
  ansible.builtin.dnf:
    name:
      - btop
      - fastfetch
      - curl
      - wget
      - nginx
    state: present

- name: Check if user in docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
