---
- name: Dnf cache
  dnf:
    update_cache: true

- name: Update
  dnf:
    state: latest

- name: Packages
  dnf:
    name:
      - btop
      - fastfetch
      - curl
      - wget
      - nginx

- name: Check if user in docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  ignore_errors: true
