---
- name: Add Docker
  ansible.builtin.dnf:
    name: Docker repo
    description: Docker Repository
    baseurl: https://download.docker.com/linux/fedora/docker-ce.repo
    enabled: true
    gpgcheck: true
    gpgkey: 060A 61C5 1B55 8A7F 742B 77AA C52F EB6B 621E 9F35

- name: Install Docker
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - docker-compose
    state: present
    update_cache: true

- name: Create docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Start and enable Docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Test Docker
  ansible.builtin.command: docker --version
  register: docker_version
  become: true
  become_user: "{{ ansible_user }}"
  changed_when: false

- name: Display Docker version
  ansible.builtin.debug:
    var: docker_version.stdout
