---
- name: Add Docker
  ansible.builtin.yum_repository:
    name: "Docker"
    description: "Docker Repository"
    baseurl: "https://download.docker.com/linux/fedora/$releasever/$basearch/stable"
    enabled: true
    gpgcheck: true
    gpgkey: "https://download.docker.com/linux/fedora/gpg"

- name: Install Docker
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Create docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Start and enable Docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Test Docker
  ansible.builtin.command: docker --version
  register: docker_version
  become: true
  become_user: "{{ ansible_user }}"
  changed_when: false

- name: Display Docker version
  ansible.builtin.debug:
    var: docker_version.stdout
